First attempt
Seva144/java-shareit pull request #1
Opened 2023-03-18 13:21 UTC by Seva144

2023-03-19 15:35 UTC, ErkinKasymaliev requested changes
привет, оставил комменты

2023-03-19 15:35 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    private int id;
id всегда желательно делать long

2023-03-19 15:35 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    public static class Builder {
лучше заюзайте аннотацию @Builder

2023-03-19 15:35 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    public static class Builder {
лучше заюзайте аннотацию @Builder

2023-03-19 15:35 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/ItemStorage.java
> +public interface ItemStorage {
лучше все storage переименуйте в SomeDao или SomeRepository

2023-03-19 15:35 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        int owner = Integer.parseInt(userId);
не надо так делать, просто во входном параметре укажите long (так как все id желательно чтобы были long).

2023-03-19 15:35 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        if (idItem == null) throw new ValidationException("User not found");
PathVariable на null проверять не надо, так как если его не укажут, то этот контроллер просто не вызовется

2023-03-19 15:35 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        int owner = Integer.parseInt(userId);
смотрите коммент выше

2023-03-19 15:35 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        if (text.isEmpty()) throw new NotFoundException();
сделайте так @RequestParam(required = true) Optional<String> text

2023-03-19 15:35 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    @ResponseStatus(HttpStatus.CONFLICT)
handler уберите в отдельный класс. Он должен обрабатывать все ваши контроллеры

2023-03-19 15:35 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        if (text.isEmpty()) {
оставил коммент а ItemController

2023-03-19 15:35 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        if (userStorage.getUser(id) == null) throw new NotFoundException();
так как в контроллере userId стоит в RequestHeader, то валидация там и пройдет, здесь лишняя проверка

2023-03-19 15:35 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        if (userStorage.getUser(id) == null) throw new NotFoundException();
тут надо проверять есть ли юзер в хранилище

2023-03-19 15:35 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/InMemoryItemStorage.java
> +            return items.get(id);
просто return items.get(id); в сервисе уже проверите item на null. И зачем вы бросаете RuntimeException? у вас же есть NotFoundException

2023-03-19 15:35 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public User updateUser(@Valid @PathVariable("id") Integer id, @RequestBody Map<String, Object> fields)
так не пойдет. вместо Map<String, Object> fields создайте dto класс и там накиньте валидационных аннотаций

2023-03-20 21:18 UTC, Seva144 commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        if (text.isEmpty()) {
Здесь не получается по другому мне необходимо вернуть по тестам пустой список, а если просто валидировать параметр то вернет ошибку

2023-03-21 20:37 UTC, closed without merging