add-booking
Seva144/java-shareit pull request #10
Opened 2023-04-15 17:30 UTC by Seva144

2023-04-16 12:41 UTC, ErkinKasymaliev requested changes
привет, оставил комменты.

2023-04-16 12:41 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/booking/BookingMapper.java
> +public class BookingMapper {
давайте заюзаем MapStruct

2023-04-16 12:41 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +    Long validBooking(Long id);
вот этот метод и аналогичные в других репозиториях - Синтаксическйи сахар) Просто используйте готовый метод
Optional<Booking> findById(id)  - и если Optional пустой, то значит не существует объекта

2023-04-16 12:41 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if (bookingDto.getStart().isAfter(bookingDto.getEnd()) ||
это проверка на валидацию входящих данных в контроллер, другие проверки в бд, их не надо смешивать.
Попробуйте для этой проверки написать свою аннотацию (это будет круто) или вынести в отдельный метод

2023-04-18 19:51 UTC, Seva144 commented
Привет Эркин! Сделал с MapStruct но заваливает тесты на гитхаб, в пачке в группе говорят что у многих такая проблема?  Хотя локально все тесты проходит

2023-04-19 03:58 UTC, ErkinKasymaliev requested changes
привет, наверно ты mapstruct неправильно реализовал, попробуй сравнить результаты маппинга mapstruct со старой имплементацией.
Если будут трудности, то отправляй работу со старым маппингом

2023-04-19 04:55 UTC, ErkinKasymaliev commented
у тебя ошибка - неверно реализован обработчик ошибок

2023-04-20 20:35 UTC, Seva144 commented
Добрый вечер Эрикин! Можно пожалуйста как нибудь с тобой связаться в пачке или по почте?
Куратор сказал что ошибка у меня в Handler, но я что-то не понимаю суть ошибки (пропущен обработчик для Exception / Throwable), но у меня нет класса с расширением extend Exception
И опять же тесты валит - вот с этим я вообще ничего не понимаю уже много делал разных вариантов пуша с разными комбинациями логинов и паролей и портов но все равно, не проходит
Начинаю уже переживать, что ничего не успеваю сдать в этом модуле

2023-04-21 04:35 UTC, ErkinKasymaliev requested changes
привет, оставил комменты

2023-04-21 04:35 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/exceptions/ErrorHandler.java
тут не хватает пару обработчиков, поэтому сборка и падает.
`@ExceptionHandler
	@ResponseStatus(HttpStatus.BAD_REQUEST)
	public ErrorResponse handleThrowable(final MethodArgumentNotValidException e) {
		log.info("400 {}", e.getMessage(), e);
		return new ErrorResponse(e.getMessage());
	}`

2023-04-21 04:35 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/exceptions/ErrorHandler.java
`@ExceptionHandler
	@ResponseStatus(HttpStatus.INTERNAL_SERVER_ERROR)
	public ErrorResponse handleThrowable(final Throwable e) {
		log.info("500 {}", e.getMessage(), e);
		return new ErrorResponse(e.getMessage());
	}`

2023-04-21 18:54 UTC, ErkinKasymaliev commented
ну ты все починили), отправляй на проверку

2023-04-21 18:54 UTC, Seva144 commented
Привет Эркин! Вообщем выяснил из-за чего падала сборка, это не из-за обработчиков, их добавил конечно же и мне понравилось как проект ошибки теперь выводит в postman, хорошая штука. Проблема была в pom! При MapperStruct добавляется plugin и он как раз создает все эти классы интерфейсов, не знаю в чем суть но видимо эти структуры не позволяли корректно пройти тесты здесь на GitHub

2023-04-22 15:13 UTC, ErkinKasymaliev approved these changes
привет, работа принята

2023-04-22 16:54 UTC, merged