add-item-requests1
Seva144/java-shareit pull request #11
Opened 2023-04-28 20:02 UTC by Seva144

2023-04-30 15:12 UTC, ErkinKasymaliev requested changes
привет, отличная работа. оставил один коммент, он рекомендационный, желательно пару раз его использовать

2023-04-30 15:12 UTC, ErkinKasymaliev commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +                        is(bookingDtoResponse.getItem().getName()), String.class));
если вы что то мокаете, то желательно еще использовать метод verify. в данном случае
verify(bookingService, times(1)). bookingService.createBooking(any()). Здесь вы проверяете, что ваш контроллер здесь вызвал нужный метод сервиса нужное кол-во раз. Так же можно использовать при тестировании сервисов - там вы мокаете например методы репозиториев и также проверяете

2023-04-30 17:32 UTC, Seva144 commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +                        is(bookingDtoResponse.getItem().getName()), String.class));
Привет! прочитал замечание более внимательно и увидел times(1), а уже отправил на проверку и там без times

2023-05-01 09:45 UTC, ErkinKasymaliev approved these changes
привет, работа принята

2023-05-01 09:45 UTC, ErkinKasymaliev commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +        verify(bookingService).createBooking(any(BookingDtoRequest.class), anyLong());
здесь еще было бы лучше добавить times

2023-05-01 18:51 UTC, merged