Add controllers
Seva144/java-shareit pull request #5
Opened 2023-03-21 21:29 UTC by Seva144

2023-03-21 21:36 UTC, Seva144 commented
Добрый вечер Эркин!
Пришлось заново создать ветку, так как были ошибки при проверке в git. Куратор сказал так сделать
Если что прешлая проверка в закрытом pull Request First Attempt, надеюсь он у тебя виден
Там оставил некоторые комментарии еще

2023-03-22 15:54 UTC, ErkinKasymaliev requested changes
привет, многие комменты с прошлого ревью не исправлены. И не используйте здесь Reflection

2023-03-22 15:54 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/InMemoryItemRepository.java
> +        if (items.containsKey(id)) {
смотрите коммент в прошлом ревью

2023-03-22 15:54 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +                .forEach(item -> itemsDto.add(ItemMapper.mapToDto(item)));
тут лучше использовать map. map(item -> ItemMapper.mapToDto(item).collect(Collectors.tolist);

2023-03-22 15:54 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ItemDto patchItem(@PathVariable("idItem") Long idItem, @RequestBody Map<String, Object> fields,
смотрите коммент в прошлом ревью

2023-03-22 15:54 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public List<ItemDto> searchItemByText(@RequestParam Optional<String> text) {
просто string

2023-03-22 15:54 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/user/UserService.java
> +            ReflectionUtils.setField(field, excitingUser, value);
не используйте в этом проекте Reflection

2023-03-23 20:18 UTC, closed without merging